services:
  backend:
    image: lngngyn/it4409-backend:latest   # thay build bằng image
    container_name: nestjs_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - /home/ec2-user/backend/.env        # đường dẫn trên EC2